### ISSUE TITLE
Signs "Team-Blue and Team-Red" doesn't work.

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/BlockBall#101]
Hi,

The signs TeamBlue and TeamRed doesn't work if we do a right click on them.

Could you fix it ?
Thanks ! :D

**Comment by TheIntelloBox** [comment]
Why it doesn't work for a minigame ?

**Comment by Shynixn** [comment]
Selecting the team via the team sign is indeed possible after you have joined the lobby. It isn't possible as it would feel strange not being able to join a almost full lobby when you click on a full team. The most common usecase for team selection is after joining the game and clicking on a basic join sign on a hub or so.
