### ISSUE TITLE
Is it possible to force even teams?

### ISSUE THREAD

**Issue by mibby** [Shynixn/BlockBall#11]
Using v3.8.0.

**Comment by Shynixn** [comment]
Depends what you mean, there is a hidden gamemode called event where you can pre setup teams as admin and all added players are teleported when the admin starts the game.

**Comment by mibby** [comment]
I'd like to keep games automated if at all possible. Just a simple check to see if teams would be starting uneven would be nice. Such as to prevent 6 (red) vs 4 (blue), force a random person to the blue team. Or if a game is 5v4, cancel countdown start-up or restart it until the game has even teams.

**Comment by Shynixn** [comment]
I can certainly understand the problem of uneven teams, a simple option to force even teams would be a nice improvement.

**Comment by Shynixn** [comment]
Added option to the latest snapshot 4.0.1 (blockball-4.0.1-20170707.144323-1-jar-with-dependencies.jar)
