### ISSUE TITLE
Ball Dissapearing

### ISSUE THREAD

**Issue by DatGamertje** [Shynixn/BlockBall#113]
Whenever a game is going on in the minigame mode and a player quits the server which was playing, the ball just dissapears when a goal has been made and everyone has respawned at their team spawn locations.

I'm using a 1.12.2 paperspigot server, the plugin runs on version 5.2.0, it's using MySql to store the data and I have setup a limit to a minimal of 2 players on each team with a max of 4.
I didn't upgrade yet to the 5.3.0 version since it doesn't have a bugfix for this issue so it shouldn't matter too much anyway I think.

**Comment by Shynixn** [comment]
Thanks again for reporting, the minigame mode actually used the conditions for hubgame if the ball should spawn or not. Should be fixed next version.
