### ISSUE TITLE
1.13 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/BlockBall#117]
Hey Christoph !

https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-pre7-development-builds.328883/

You can now start to update BlockBall to 1.13. :D

**Comment by Shynixn** [comment]
Hi TheIntelloBox!

Sure, the compatibility layers in BlockBall already exist and it shouldn't be a problem to support 1.13. However, I will start working on it once the official version is released.

**Comment by TheIntelloBox** [comment]
Hey Christoph,

1.13 is released. :)

**Comment by Shynixn** [comment]
Thanks, I have done some testing with 1.13-pre7 and PetBlocks so the BlockBall update should not be a problem.

**Comment by TheIntelloBox** [comment]
5.4.0 adds compatibility for 1.13 ? :)

**Comment by Shynixn** [comment]
Yes, it does.

**Comment by Shynixn** [comment]
@TheIntelloBox I forgot to append something to the developer notes regarding WorldEdit. Please stay in touch.

**Comment by TheIntelloBox** [comment]
@Shynixn Okay ty
