### ISSUE TITLE
Is it possible to adjust the double-jump distance?

### ISSUE THREAD

**Issue by mibby** [Shynixn/BlockBall#12]
My map isn't that large so the double-jump catch-up mechanic is quite overpowered. Is there any way to adjust the distance / thrust power you go when you double jump? As I can't seem to find a setting for it.

**Comment by Shynixn** [comment]
I have looked it up, no it's currently not possible to change the velocity power. I should be able to add that though.

**Comment by mibby** [comment]
Thanks. That is one of the biggest complaints from my players, that the double jump distance is too strong making it easy to cross over the entire map too quickly.

**Comment by Shynixn** [comment]
Added option to the latest snapshot 4.0.1 (blockball-4.0.1-20170707.144323-1-jar-with-dependencies.jar)
