### ISSUE TITLE
Ability to control the vertical direction of kick

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/BlockBall#125]
Moved issue because of the deprecation of the Ball project.

#https://github.com/Shynixn/Ball/issues/19

@LazoYoung

**Comment by LazoYoung** [comment]
Duplication: This thread should be merged into #214

**Comment by LazoYoung** [comment]
@Shynixn Can you assign this issue to me?

**Comment by LazoYoung** [comment]
I forgot to state Fixed in the commit message. Could you close this issue, please?
