### ISSUE TITLE
About scoring difficulty

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/BlockBall#127]
Moved issue because of the deprecation of the Ball project.

#https://github.com/Shynixn/Ball/issues/9

@LazoYoung

**Comment by Shynixn** [comment]
I think it's now a way more precise with the new NMS layer but requires futher testing.

**Comment by LazoYoung** [comment]
## Current progress
- [ ] Refactor the hitbox detecting collision with blocks (Not entity)
- [x] Put a short delay for interaction when a ball gets kicked

**Comment by LazoYoung** [comment]
I had tested the latest snapshot. For my opinion in this snapshot, the block knockback collision works much smooth than before.

**Comment by Shynixn** [comment]
Thanks for testing it. I'll move this issue to the snapshot column.
