### ISSUE TITLE
Possible to allow changing settings in-game without broadcasting in chat?

### ISSUE THREAD

**Issue by mibby** [Shynixn/BlockBall#13]
When you type numbers and letters to adjust the settings / save the arena / go back, it is being broadcasted in chat to all players on the server. This can get quite spammy, especially if you have one synced up network global chat. 

Would it be possible to allow for settings to be changed via command instead?

**Comment by Shynixn** [comment]
I have already added a command for such a case as it can get very messy with other chat plugins. 

Go to the config.yml and set the following command enabled: true. Simply navigate through the menu by typing **/bbc <number/text>** afterwards.

_navigate-chatmenu:
  enabled: false
  command: bbc
  useage: /<command>
  description: Helps navigating through the chamenu.
  permission: blockball.admin
  permission-message: You don't have permission_

**Comment by mibby** [comment]
Thanks, I must have overlooked that setting. :)
