### ISSUE TITLE
Trouble with worldedit wand behavior

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#132]
When I left click a block with wand, the block gets destroyed. This happens only with the latest blockball plugin installed.

**Comment by Shynixn** [comment]
The block breaks when hitting it with the WorldEdit axe only on server with BlockBall installed? Very strange behaviour..

**Comment by LazoYoung** [comment]
Yes exactly. It was discovered by my fellow player. I can also confirm this issue.

**Comment by LazoYoung** [comment]
My server is running on spigot 1.13.1 and the worldedit is 7.0.0 beta 1

**Comment by Shynixn** [comment]
The snapshot bot should publish the snapshot fixing this issue soon. Thanks for reporting!

**Comment by LazoYoung** [comment]
GJ :D
I'm facing two exams this weekend so I won't be able to review the fix

**Comment by Shynixn** [comment]
That's fine. Good luck!

**Comment by LazoYoung** [comment]
The issue apparently is fixed in my test
