### ISSUE TITLE
Save spectator settings leads into setting title settings.

### ISSUE THREAD

**Issue by mibby** [Shynixn/BlockBall#14]
When I hit 3 to save spectator settings, it loads the chat output to set arena title/subtitle and bossbar/scoreboard settings instead of saving.

Oddly saving vault settings lead into setting max score / max players screen as well. Perhaps it is parsing the number for a specific page instead of the active one instead?

**Comment by Shynixn** [comment]
Checking it.

**Comment by Shynixn** [comment]
* Fixed in the latest snapshot
