### ISSUE TITLE
"cannot find command" when trying to create arena

### ISSUE THREAD

**Issue by Xenorio** [Shynixn/BlockBall#147]
When i try to create an arena by typing "/blockball" and then clicking on the "create" link, i get the following error: "Cannot find command."

The console tells me that clicking the create link executed "/blockball template open". When i try to execute that command manually, it's giving me the same error.

Server: Spigot 1.12.2
Blockball: 6.3.0

Here's an error stack that the console gave me: https://pastebin.com/pRPwQbgD

**Comment by Shynixn** [comment]
Thanks for reporting, this issue is caused by #146. There will probably a hotfix in the next few days.

**Comment by LazoYoung** [comment]
This issue is revived again in the recent version, and was reported by a member of our discord channel.
I've pinned the conversation in discord so you can check it out.
[Error log](https://pastebin.com/ZBMhHRm7)
