### ISSUE TITLE
No option to set a spectate location.

### ISSUE THREAD

**Issue by mibby** [Shynixn/BlockBall#15]
I can't seem to find an option to set a spectate location, only a spectate radius. Would it be possible to allow setting a spectate location so when the sign is hit while the game is in-progress, they are brought to the spectate location, then back to the leave location when the game ends?

**Comment by Shynixn** [comment]
I think the specate radius is the radius where other players running/sitting around the arena receive all messages and scoreboard updates from the game. You could setup a warp with a warp plugin to teleport to an arena.

**Comment by mibby** [comment]
Wouldn't it make more sense to have the plugin handle a spectate state of players to watch games? i.e. When trying to join via sign if a game already started, be brought to a spectate spawn location with game updates broadcasted to players in this spectate 'state' rather than in a radius of a specific location.
