### ISSUE TITLE
Setting blue/red goal corners does not update properly, despite a larger region selection and saving the arena.

### ISSUE THREAD

**Issue by mibby** [Shynixn/BlockBall#16]
I set a larger blue and red goal corner but it did not update correctly in the config. Tried numerous times and hit the number to save the arena, but the old values still persisted in the configuration. I do not think the config is updating / saving correctly.

**Comment by Shynixn** [comment]
Are there any error logs you can provide or is it just not updating?

**Comment by mibby** [comment]
There are no error logs. The region selection when redefining the corner selection for the goals just doesn't update in the config when typing the command. Have to change the coordinate numbers manually in the config.

**Comment by Shynixn** [comment]
Cannot recreate this issue. Is this problem still present in the latest Snapshot?
