### ISSUE TITLE
Shooting the ball

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#18]
A ball gets kicked when a player touches it, but it does not go far.
It's quite boring for this player to dribble the ball through the huge playground, isn't it?
So here's my suggestion:

- If a ball collided with a player = the player is dribbling the ball.
  - **Meantime the ball is hit by the player** = he is shooting the ball.

**Comment by Shynixn** [comment]
Hi LazoYoung!

Seems like a good idea adding something like this, still you can already modify the ball's vertical and horizontal strength for bigger fields. I think the default value is 1.8 for horizontal and 0.8 for vertical, I would recommend setting it between 5.0 and 0.1 depending on the size of your field.

**Comment by Shynixn** [comment]
Added the alpha version of ball engine v2 to blockball-4.1.0-20170729.133646-1-jar-with-dependencies.jar

**Comment by LazoYoung** [comment]
Good to hear that news! will try that tomorrow as it's night time here ;)

**Comment by LazoYoung** [comment]
It is working just like what I wanted!  
But I wonder why the ball sometimes (like usually) stop moving and just spinning around  
after it was kicked and then hit the ground? It makes me extremely hard to score in front of the net xD

**Comment by Shynixn** [comment]
Glad that you like it as it took many months for me to add it since you have opened this ticket. 

Yes, there are still many movement problems, the ball stops moving or the rolling distance goes crazy some  time. I'll try to modify it a little bit every update so it gets more stable and can replace the current engine.

**Comment by Shynixn** [comment]
I would like to keep it open, so I won't forget working on it.

**Comment by Shynixn** [comment]
- Ball Physic engine added in 5.0.1
