### ISSUE TITLE
BlockBall axe sends messages to normal users

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/BlockBall#187]

**Comment by Ainashi** [comment]
Hello, it's problem about which I was talking on Discord :) If you need information about versions on my server:
- This server is running CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- Tested versions of BlockBall: 6.4.0 and 6.8.0
Bug appeared in both of them.

**Comment by Shynixn** [comment]
Thanks for your detailed report. I'll try to publish a snapshot soon fixing this issue.
