### ISSUE TITLE
Spectatormode players can hit the ball

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/BlockBall#188]

**Comment by LazoYoung** [comment]
Does the title indicates that the players who're in the spectator game-mode? or the spectators in a blockball arena?

**Comment by Shynixn** [comment]
People using the BlockBall spectator mode and getting set to gamemode spectator

**Comment by LazoYoung** [comment]
But /bbspectate doesn't work with no error message so I'm unable to verify this.

**Comment by Shynixn** [comment]
There is no /bbspectate. I mean the spectator mode you can only use via the Minigame Mode. This issue will be closed next release as it was never confirmed by the reporter.
