### ISSUE TITLE
Lag after certain amount of time (In my case after the second goal)

### ISSUE THREAD

**Issue by mesl** [Shynixn/BlockBall#193]
Hi there,

I've recently installed and set-upped your plugin on my main server, On my main server everything runs fine except after a certain amount of time (In my case after the second goal) the ball start becoming laggy and doesn't roll as smoothly as it did before that, (It teleports back and forth, It rolls in a Z pattern, etc)

Before I posted this issue I checked if it does that as well in a clean environment so I set-upped your plugin at my test server and the same did happen again

My servers are both running 16GB ram and the latest gen i7 processor

I hope you can take a look at this,
Kind regards,
Merlyn

**Comment by LazoYoung** [comment]
May I ask you to provide us your lag-monitor data?
If you're using Spigot you can use /timings to dump a timing data.

**Comment by mesl** [comment]
Thanks for your fast response

This is the timings report for the main server
https://pastebin.com/kgyUfmXx

This is the timings report for the test server
https://pastebin.com/U5XXkBdM

This is the timings paste for the main server
https://timings.spigotmc.org/?url=qofarujegi

This is the timings paste for the test server
https://timings.spigotmc.org/?url=osayodapen

Kind regards

**Comment by Shynixn** [comment]
Thank you. I'll test it once I am back from vacation.

**Comment by mesl** [comment]
Thank you very much,

Have a nice vacation btw

**Comment by Shynixn** [comment]
Thank you. I am now back from my vacation. @mesl 

This is a difficult issue, I am not sure if I can replicate this correctly. Even the timings you sent us seem to be fine and BlockBall performs fast on it. Anyway, I tried minor performance optimizations but they don't seem to change much. 

Can you please try the following testsetup and send us the timings again? (The spigot links are probably enough and easier to read)

- Use the latest BlockBall v6.10.0-SNAPSHOT (https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/blockball/blockball-bukkit-plugin/6.10.0-SNAPSHOT/blockball-bukkit-plugin-6.10.0-20190809.180722-12.jar)
- After starting the server, join and execute "/timings on"
- Create a Hubgame and play until you get the performance problems
- Leave the Hubgame and execute "/timings paste"
- Send us the generated url

**Comment by mesl** [comment]
Thank you for your answer,

I've created a hubgame and played it (Probably configured something wrong because everytime i joined on my main and walked a bit i got kicked, so i joined with my main and played with my alt)

This is the paste link generated:

https://timings.spigotmc.org/?url=gebuyesuqa

Kind regards,
Merlyn

**Comment by Shynixn** [comment]
Thank you for your detailed report. 

However, the timings do not really give a clue what performance problems appear on your side. BlockBall performs very fast as expected with your setup.  
Average TPS: 19.99/20.00 is also a great value with a MiniGame plugin installed. 

Sorry, I do not know how I can help you any further. There weren't any other performance reports in the last 2 years and I am unable to replicate it on my own server.

**Comment by mesl** [comment]
Thank you for your time to take a look at the issue again,

Should I try to record the bug? Maybe that will help

Thank you and kind regards
Merlyn

**Comment by Shynixn** [comment]
Hm... maybe? Can you also try the solutions mentioned on this page? Maybe changing the relocation distance fixes this issue.

**Comment by mesl** [comment]
I tried settings the value to 1.0, Still the weird lag, Also made a new timings paste:

https://timings.spigotmc.org/?url=oqoliveces
I will now try to record the issue

Kind regards,
Merlyn

**Comment by mesl** [comment]
Here's the recording

https://www.mediafire.com/download_status.php?quickkey=50s9i1okvqnguse&origin=download

Kind regards,
Merlyn

**Comment by LazoYoung** [comment]
I see the ball teleporting backwards whenever it stops by friction. Is this what you mean by "lag"?
But your timings indicate that the server's performance is OK.
I suppose that blockball engine is malfunctioning under certain condition so we probably need a feature to debug a ball parameters to measure what's misbehaving...

**Comment by Shynixn** [comment]
Thank you for the video. I think Lazo got the right idea, the BallForceField implementation uses some kind of (normally) invisible ball teleport replaying in order to calculate knockback values without world collisions.

I'll submit a snapshot where the collision cache gets cleaned up each ball respawn (instead of each game restart). Maybe this is the issue...?

In the meanwhile @mesl you can try to hold a barrier in during a BlockBall game and take a look if barriers are spawning at the places where the ball teleports back.

**Comment by Shynixn** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/blockball/blockball-bukkit-plugin/6.10.0-SNAPSHOT/blockball-bukkit-plugin-6.10.0-20190812.171425-18.jar

You can try the following: 
1. Just install the snapshot above and see if it works now.
2. If it does not work, try investigating it with the barrier in your hands
3. If it still does not work enable the debug flag in the config.yml and send me the server log

**Comment by mesl** [comment]
I will test this tomorrow, thank you. Just arrived at my vacation so sorry for the delay

Kind regards
Merlyn

**Comment by LazoYoung** [comment]
From my 1.14 server's perspective, I have no issue with the ball throughout a whole game. Clearly there were few Barriers generated and they would not disappear. But those barriers only appear at the edge of the field so I guess barriers may not be the case.

**Comment by Shynixn** [comment]
The per ball cache clear is unsafe and may leave barriers around the field. If it is the solution I will clean it up correctly.

I also cannot replicate this issue Lazo ._.

**Comment by mesl** [comment]
I asked some of my staff and they said that the barrier would spawn in the lag scenarios, I cannot confirm yet because I haven't got any time to test yet

(Also something to note, my server runs 1.12.2)

Kind regards,
Merlyn

**Comment by mesl** [comment]
Okay so i've tested it with the barrier and the barrier doesn't get placed on the laggy places (So i think the barrier behalves normal)

Here are the timings during the debug:
https://www.spigotmc.org/go/timings?url=ivejagafof

here's the debug log:
[latest (1).log](https://github.com/Shynixn/BlockBall/files/3498638/latest.1.log)


Kind regards,
Merlyn

**Comment by LazoYoung** [comment]
I tested with the same environment that you presented (spigot 1.12.2, clean installed server).
And the result was quite different: No lag, No suspicious Ball movement throughout a whole game.
@mesl I need your arena file to fully replicate your situation.

**Comment by mesl** [comment]
Hello,

Here's my BlockBall folder:
[BlockBall.zip](https://github.com/Shynixn/BlockBall/files/3501088/BlockBall.zip)

Kind regards,
Merlyn

**Comment by Shynixn** [comment]
@mesl 

Please release the arena, you should select a cube instead of a square. Take a look at the y value.

Your arena file:
```code
  corner-1:
    world: Soccer
    x: -15.0
    y: 69.0
    z: -61.0
    yaw: 0.0
    pitch: 0.0
  corner-2:
    world: Soccer
    x: -145.0
    y: 69.0
    z: -139.0
    yaw: 0.0
    pitch: 0.0
````

Expected arena file:
```code
  corner-1:
    world: Soccer
    x: -15.0
    y: 69.0
    z: -61.0
    yaw: 0.0
    pitch: 0.0
  corner-2:
    world: Soccer
    x: -145.0
    y: 120.0
    z: -139.0
    yaw: 0.0
    pitch: 0.0
```

**Comment by mesl** [comment]
Thank you, That fixed the issue!

Kind regards
Merlyn
