### ISSUE TITLE
'You left the game.' is outputted twice when exiting a BlockBall lounge via exit sign.

### ISSUE THREAD

**Issue by mibby** [Shynixn/BlockBall#20]
blockball-3.8.1-20170303.142405-2.jar

![link1](http://i.imgur.com/q0S6Op5.png)
![link2](http://i.imgur.com/ohEzxqM.png)

**Comment by Shynixn** [comment]
This build seems to contain various problems. Thanks for the screenshots, fixing it.

**Comment by Shynixn** [comment]
* Should be fixed in the latest snapshot
