### ISSUE TITLE
Inventory is carried over across worlds into the lounge when right clicking a join sign with an item and when the item opens a GUI.

### ISSUE THREAD

**Issue by mibby** [Shynixn/BlockBall#21]
blockball-3.8.1-20170303.142405-2.jar

I have it configured so players have a separate inventory in the Hub world and in the world where the BlockBall lounge / arena is located. So players who join a BlockBall game shouldn't carry over their inventory, gamemode, xp, health, etc. from the former world. However, if you right click the BlockBall join sign with an item from the other world, it will carry over that item / inventory into the lounge.

Would it be possible for items to not carry over into the lounge / separate world when hitting the join sign with it? To have an empty inventory when in the lounge.

Video example.
https://www.dropbox.com/s/ov2n0n8h39zqotd/2017-03-15%2002-09-31.mkv?dl=0

**Comment by Shynixn** [comment]
That's because the inventory is storred as soon as the player hits the sign. There might be the case that the arena is in the same world. Still, it's something I would consider supporting in the future.

**Comment by mibby** [comment]
The arena isn't in the same world though. Just the sign is in the world with the inventory and the inventory only carries over when hitting the sign with an item. Empty-handed hitting doesn't carry over the inventory. It is quite odd.

**Comment by Shynixn** [comment]
- Changed the way how the temporary storage works. Should be working in the latest snapshot.
