### ISSUE TITLE
It's unable to throw a ball

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#210]
https://github.com/Shynixn/BlockBall/blob/b4aaff62233af56a07deaa36d2b72516f69c3929/blockball-bukkit-plugin/src/main/java/com/github/shynixn/blockball/bukkit/logic/business/proxy/BallProxyImpl.kt#L309

In the third phrase, == should be corrected to != and comparing uniqueId for identifying is preferable.

**Comment by Shynixn** [comment]
Are you sure with that? Also, id comparison is not necessary as CraftEntity overrides the equals method where the id gets compared.

**Comment by LazoYoung** [comment]
Oh I didn't know that equals method does the job.
But yeah I confirmed that == halts the method, preventing balls from getting thrown by players.

**Comment by LazoYoung** [comment]
Oh, looks like I misplaced the argument with the ball itself where I called this method. Sorry :P
