### ISSUE TITLE
Implement elastic force to bounce on ground

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#233]
Assign the issue to me please.
Do you think we need an extra modifier to adjust the force? Ball modifier page is about to overflow out of the chat box

**Comment by Shynixn** [comment]
Yes, if its value has an impact on the gameplay.

**Comment by Shynixn** [comment]
If you are confortable with adding a new page you can add a new one otherwise I'll take a look later on how to structure it.

**Comment by LazoYoung** [comment]
Okay. Default value is going to be assigned with 0 which turns off the bouncing effect.

**Comment by Shynixn** [comment]
If playing with a set  "feels better" I would not turn it off per default.

**Comment by LazoYoung** [comment]
Okay I'll take it into account.
