### ISSUE TITLE
Blocks sometimes disappear when being hit by a ball

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/BlockBall#234]

**Comment by LazoYoung** [comment]
I have a feeling that barrier wall might be the cause of this

**Comment by Shynixn** [comment]
That's the only part wherr blocks get removed but I thought it checks if it is AIR first. Can you confirm this issue Lazo?

**Comment by LazoYoung** [comment]
No I haven't seen any block vanishing during the game, but I'll keep an eye on it.

**Comment by LazoYoung** [comment]
Did someone in the internet found and reported the issue or is it you?
