### ISSUE TITLE
Unable to launch a container with pre-defined dockerfile

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#256]
```
Done

Step 1/5 : FROM openjdk:8
 ---> cb8daa634f73
Step 2/5 : WORKDIR /minecraft
 ---> Using cache
 ---> 30eff36159f3
Step 3/5 : COPY ["blockball-tools", "blockball-bukkit-plugin/build/libs", "./"]
Error response from daemon: COPY failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder090569653\blockball-tools: The system cannot find the file specified.
Failed to deploy '<unknown> Dockerfile: blockball-bukkit-plugin/blockball-bukkit-nms-115R1/Dockerfile': Can't retrieve image ID from build stream
```

I've made sure to have every dependencies ready before the launch.
I suspect that **blockball-tools** must be an existing directory under the context but it isn't.

**Comment by Shynixn** [comment]
Use the root BlockBall folder as context folder. I'll send you a screenshot on discord.

**Comment by LazoYoung** [comment]
Thanks for the advice. It's now running without issue.
Do you mind if I ask you to elaborate on explaining this point in readme.md?

**Comment by LazoYoung** [comment]
I guess the discussion is over so I'm closing this thread.

**Comment by Shynixn** [comment]
Yes, I will update the README.
