### ISSUE TITLE
Glitchy ball movement

### ISSUE THREAD

**Issue by James76931** [Shynixn/BlockBall#259]
Hi.

For some reason the ball in my arena is moving around really weirdly. I'm using version 6.13.0 of the plugin with PaperSpigot build 120 (for 1.15.2.)

Here's a video of what I mean: https://youtu.be/64PPd7tjWAo

**Comment by rowanplayzYT** [comment]
Im having the same problem pls fix

**Comment by Shynixn** [comment]
You can try to disable bouncing in the arena.yml files. 
``
    ball:
      always-bounce: false
``

**Comment by rowanplayzYT** [comment]
I tried doing that and it did nothing (and yes I reloaded blockball after making the changes)

**Comment by LazoYoung** [comment]
@rowanplayzYT Could you pm me in Discord? I'd like to meet you and check out the server and its configuration.

**Comment by LazoYoung** [comment]
@James76931 @rowanplayzYT 
I'm sorry to be late but please confirm that your arena field is properly configured.
Remember when you selected the area of field using WorldEdit? Make sure you've selected 2 points of blocks **with different height in Y-axis**.
It seems that this glitch is triggered by this kind of wrong configuration.

**Comment by Shynixn** [comment]
Might be related to the PaperSpigot version.

**Comment by Shynixn** [comment]
https://github.com/PaperMC/Paper/issues/3401
