### ISSUE TITLE
Stuttering ball movement

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#261]
If you kick the ball and then eventually when there's no player nearby (approx. 5 meters), the ball becomes frozen and wait until a player comes closer. So it looks stuttering.
Is it intended behavior?

**Comment by Shynixn** [comment]
The ball runs on the entity-tick cycle of spigot. This optimizes performance as the ball movement is not executed every tick. I think the value to change that is called ``entity-activation-range`` in the spigot.yml file https://www.spigotmc.org/wiki/spigot-configuration/.

**Comment by LazoYoung** [comment]
I wonder if you have mentioned this info in documentation? Otherwise I'll write it for you
