### ISSUE TITLE
Commands don't work?

### ISSUE THREAD

**Issue by No1InParticular** [Shynixn/BlockBall#30]
Commands don't work?

Spigot says these are commands:
/bbjoin <game> <team> - Join any game from anywhere (new v2.8.0)
/bbc - Optional command to navigate through the chat menu (servers with buggy chat) (new v1.3)
/bb - Optional command to join teams (servers with buggy chat) (new v1.3)

None of them works though, I noticed in your plugin.yml (on here) it doesn't have them listed as well

**Comment by Shynixn** [comment]
These are optional command and can be configured in the config.yml. You can change the command, description, permission, permission-message as you like.

Also, sorry it's my fault that you are asking this as BlockBall still lags of a complete documentation.
