### ISSUE TITLE
Unable to create BallMeta entity

### ISSUE THREAD

**Issue by 7isenko** [Shynixn/BlockBall#304]
Here are few lines of code from your templates:
```java
BallMeta ballMeta = BlockBallApi.INSTANCE.create(BallMeta.class);
BallEntityService ballEntityService = BlockBallApi.INSTANCE.resolve(BallEntityService.class);

BallProxy ballProxy = ballEntityService.spawnTemporaryBall(location, ballMeta);
```
But first line throws IllegalArgumenException: Entity could not be created.
![Скриншот 09-08-2020 173303](https://user-images.githubusercontent.com/54848757/89735244-be754880-da69-11ea-9ae0-199f00344995.jpg)

**Comment by Shynixn** [comment]
Seems like the classpath did not get updated correctly when being moved to cross platform. I'll update it.
