### ISSUE TITLE
errors after playing game

### ISSUE THREAD

**Issue by Stoniasawsome** [Shynixn/BlockBall#318]
im getting this error which lags my paper spigot 1.16.2 server i just downloaded it and added an arena. This is the errors.
[latest.log](https://github.com/Shynixn/BlockBall/files/5145594/latest.log)

**Comment by Shynixn** [comment]
Hi @Stoniasawsome !
Thank you for reporting this issue. I'll publish a snapshot fixing it...

**Comment by Shynixn** [comment]
@Stoniasawsome Can you please try the following snapshot and see if it is fixed?

https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/blockball/blockball-bukkit-plugin/6.21.0-SNAPSHOT/blockball-bukkit-plugin-6.21.0-20200829.195447-2.jar

**Comment by ScuroK** [comment]
here is what i got today after updating blockball from spigot:
[latest.log](https://github.com/Shynixn/BlockBall/files/5145969/latest.log)


i am now testing your snapshot

**Comment by ScuroK** [comment]
update: console spam seems gone so far.

**Comment by Stoniasawsome** [comment]
now when i start a game if i run to a sideline it says :you have left the game" and i start bouncing in the sky until i select a team but there is no error

**Comment by Stoniasawsome** [comment]
that was because i had my arena bounds set to far in. but when i end a game i still bounce on top of the force field

**Comment by Shynixn** [comment]
@Stoniasawsome Yes, this is the intended behaviour. There are multiple ways to configure that:

- Enable instant-forcefield-join, so players automatically join the game again after the game is over.
- Set a leave spawnpoint where players get teleported to when a game ends.

**Comment by Stoniasawsome** [comment]
im getting another problem with the ball not spawning, in the first few rounds of gameplay. This happens right out of the box with the default round times, and if you customize it too. it says this in my console when the ball is suppose to spawn. 30.08 18:52:11 [Server] INFO [BlockBall] Removed invalid BlockBall in chunk. it will spawn a ball after the switch sides but for that first 150 sec incriment you just stand there and no ball spawns
