### ISSUE TITLE
Refactor RightclickManageServiceImpl

### ISSUE THREAD

**Issue by Giancarmine** [Shynixn/BlockBall#338]
+ This service can be refactored from the `blockball-bukkit-plugin` module to the `blockball-core` module.
+  Move the class `com.github.shynixn.blockball.bukkit.logic.business.service.RightclickManageServiceImpl` class to
    `com.github.shynixn.blockball.core.logic.business.service.RightclickManageServiceImpl`
+ Remove all `org.bukkit.*` dependencies. The type of the method parameters does not need to be checked.
    Instead of Player use Any
+ Add a constructor dependency to ProxyService (take a look at other classes to find out how to do that).
+ Use the `$ProxyService.setSignLines` method to set the sign lines. (The boolean return value might be useful)
+ Make sure the project still compiles afterwards and passes all tests

**Comment by Giancarmine** [comment]
Hi there!
I have a little problem with the replacing of the `org.bukkit.*` dependencies..

```
        if ((location as Any).block.state is Any) {
            val sign = location.block.state
            sign.setLine(0, ChatColor.BOLD.toString() + "BlockBall")
            sign.setLine(1, ChatColor.GREEN.toString() + "Loading...")
            sign.update(true)

            rightClickListener[player]!!.invoke(location as Any)
            rightClickListener.remove(player)
        }
```

I am trying to replace the `location.block.state` with the `$Proxy Service.set SignLines`, to do that i have the location but i can't understand what should be lines in this case.

Any help? :sweat_smile:

**Comment by Shynixn** [comment]
Sure.

``proxyService.setSignLines(location, listOf(ChatColor.BOLD.toString() + "BlockBall",ChatColor.GREEN.toString() + "Loading...")``

Does this answer you question?

**Comment by Giancarmine** [comment]
Yeah! :rocket: https://github.com/Shynixn/BlockBall/pull/339
