### ISSUE TITLE
Refactor arena selection

### ISSUE THREAD

**Issue by nlaert** [Shynixn/BlockBall#340]
- The BlockBall plugin offers a way to select an arena via WorldEdit. However, this feature has been replaced by an own selection algorithm and is not being used anymore.
- Remove com.github.shynixn.blockball.api.business.service.DependencyWorldEditService and all implementations of it.
- Modify com.github.shynixn.blockball.bukkit.logic.business.service.BlockSelectionServiceImpl so that it no longer uses com.github.shynixn.blockball.api.business.service.DependencyWorldEditService. You can start by removing the isBlockBallAxeEnabled() function and assuming everywhere where it has been called before, it is now always true.
- Make sure to remove any other usages of the com.github.shynixn.blockball.api.business.service.DependencyWorldEditService across the project
- Make sure the project still compiles afterwards and passes all tests.

**Comment by nlaert** [comment]
Hello, sorry I'm not being able to run the downloadDependencies in a mac. have you had any issues with that?

**Comment by Shynixn** [comment]
Hi! 
This seems to be a common problem. See me reply at #336.

**Comment by nlaert** [comment]
Thanks, that helped fixing the issue. Maybe this could info could be added to README in case other people have the same issue?

**Comment by Shynixn** [comment]
> Thanks, that helped fixing the issue. Maybe this could info could be added to README in case other people have the same issue?

Yes, good idea.
