### ISSUE TITLE
RayTracing in 1.13.2+ sometimes causes an IllegalArgumentException

### ISSUE THREAD

**Issue by TOWUK** [Shynixn/BlockBall#358]
[latest.log](https://github.com/Shynixn/BlockBall/files/5647838/latest.log)
i finish one game and have this warns!

**Comment by Shynixn** [comment]
The warning itself is not harmful to your server but this will be of course fixed.

**Comment by Shynixn** [comment]
Can you please try the following snapshot and see if the problem was fixed @TOWUK ?

https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/blockball/blockball-bukkit-plugin/6.22.1-SNAPSHOT/blockball-bukkit-plugin-6.22.1-20201206.121046-2.jar

**Comment by TOWUK** [comment]
> Can you please try the following snapshot and see if the problem was fixed @TOWUK ?
> 
> https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/blockball/blockball-bukkit-plugin/6.22.1-SNAPSHOT/blockball-bukkit-plugin-6.22.1-20201206.121046-2.jar

okay i go test it, thanks!

**Comment by TOWUK** [comment]
[2020-12-06-3.log](https://github.com/Shynixn/BlockBall/files/5649247/2020-12-06-3.log)
 dont have errors after few time matches

**Comment by TOWUK** [comment]
I'm sorry, maybe either a geyser-spigot error or blockbal teleports the player to those coordinates? and then to the position from the config (lobby start and exit)

**Comment by TOWUK** [comment]
blockball use old api plugins? what is * after name plugin?
![image](https://user-images.githubusercontent.com/28830162/101288914-2cf4c800-380a-11eb-9452-da69e9b3bdc2.png)

**Comment by Shynixn** [comment]
Thanks for the feedback. I'll schedule another snapshot fixing the "moved too quickly" error.

Yes, BlockBall handles compatibility by itself and does not care about the compatibility api.
https://www.spigotmc.org/threads/asterisks-stars-in-plugin-list.370596/

**Comment by Shynixn** [comment]
There you go: @TOWUK 
https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/blockball/blockball-bukkit-plugin/6.22.1-SNAPSHOT/blockball-bukkit-plugin-6.22.1-20201206.184727-4.jar

**Comment by TOWUK** [comment]
please check it, team color name dont correctly! :(
https://youtu.be/d9_UXdIjJgw

**Comment by Shynixn** [comment]
The team color is fixed in your updated template, right?
I see, the raytracing code needs even more restrictions but that's easy.

**Comment by TOWUK** [comment]
> The team color is fixed in your updated template, right?
> I see, the raytracing code needs even more restrictions but that's easy.

-_-

**Comment by Shynixn** [comment]
I'll check it.
