### ISSUE TITLE
Add russian template

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/BlockBall#359]

**Comment by TOWUK** [comment]
i noob in github, please change file arena-ru: 
[arena-ru.zip](https://github.com/Shynixn/BlockBall/files/5649440/arena-ru.zip)

![image](https://user-images.githubusercontent.com/28830162/101290961-5ae00980-3816-11eb-8705-ad5604a02a49.png)

**Comment by Shynixn** [comment]
Done. Please, simply submit another pull request next time.
