### ISSUE TITLE
Cannot change sound/particle type for ONPASS effect

### ISSUE THREAD

**Issue by tildearrow** [Shynixn/BlockBall#381]
For some reason I am unable to change the sound effect or particle effect for the ONPASS event in the ball.

Steps to Reproduce:
1. Configure the ball.
2. Sound Effect/Particle Effect
3. Select ONPASS
4. "Selected sound/particle effect" does not appear.

**Comment by Shynixn** [comment]
Should be fixed in the latest snapshot. 

https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/blockball/blockball-bukkit-plugin/6.23.0-SNAPSHOT/blockball-bukkit-plugin-6.23.0-20210303.193325-2.jar
