### ISSUE TITLE
Option for Ball Entity (Slime) to Be Non Clip-abble

### ISSUE THREAD

**Issue by sleepymountain** [Shynixn/BlockBall#391]
I play on another football server and they use a custom plugin, the ball entity can be walked through, which allows the player to do more complex dribbling skills. Can you make this an option, or guide me in the right direction so I can fork it and have this feature.

Also, the option to be able to adjust the power and height of the ball solely based on the view height of the player. For example, they can do a dribble towards one direction while in the ball pointing downwards, and do a 180 turn towards and pass the ball the other way.

Thanks

**Comment by Shynixn** [comment]
The ball is an ordinary minecraft entity and they have got some collisions which is not possible to remove. 
I am also not sure about such advanced movements as the synchronization between the server and client takes a while (ping).
