### ISSUE TITLE
Title & bossbar messages don't working

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#40]
I'm using BlockBall v4.1, WorldEdit v6.1.7.3 in Spigot 1.12.1 server.
As I set up an arena and tested it, I realized some important in-game messages that didn't show up.
These are the broken strings
- red/blue-score-title(subtitle)
- red/blue-win-title(subtitle)
- bossbar that shows the current score (I enabled the vanilla one in arena settings, not BossBarPlugin)

[Here's the config of my arena](https://pastebin.com/hSZr50Cu)
Please correct me if I'm missing something like no dependencies or wrong configs..

**Comment by Shynixn** [comment]
Hi LazoYoung!

Unfortunately the current version shows a huge numbers of problems. I'll definitely take a look into this next weekend. 👍 

Thanks for providing me your arena config.

**Comment by LazoYoung** [comment]
I understand, I will wait for the next update. 
Thanks for your kind response and I really like your work <3

**Comment by Shynixn** [comment]
I already tested it as I'm not available next weekend. It seems like you enabled spectator messages but did not change the default radius of 0. (I'll change this ^^) So messages only in radius of zero blocks were shown.

Simple disable specators or set a radius of 50-100 blocks. 

` spectators:
     enabled: true
     radius: 100`

**Comment by LazoYoung** [comment]
Thanks for support @Shynixn! I just fixed the problem with your instruction.
But I think it's nonsense that spectator radius influences sending messages to in-game players.
And hopefully you could clean out the options by getting rid of unnecessary things.
This is a minor thing so don't rush it though ;)

**Comment by Shynixn** [comment]
Yeah actually it's nonsense, noticed it too. 

https://github.com/Shynixn/BlockBall/blob/6e1b1e25d36ca0d1cbf582353133d0ce2ddba969/src/main/java/com/github/shynixn/blockball/business/logic/game/GameEntity.java#L397
