### ISSUE TITLE
Option to modify walking speed for players in game

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#42]
In larger maps, speed boost is required to make game speed faster and fun.
Hopefully you could resolve this too in the next week or later :)

**Comment by LazoYoung** [comment]
Sorry my mistake

**Comment by Shynixn** [comment]
Would be a nice and easy improvent :)

**Comment by Shynixn** [comment]
Added to latest snapshot blockball-4.2.0-20170826.153752-2-jar-with-dependencies.jar

**Comment by Shynixn** [comment]
- Ball Physic engine added in 5.0.1
