### ISSUE TITLE
Teleport to the centre of arena after someone scores.

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#43]
What I suggest is that players should be teleported to the centre after one of them scores.
Spawnpoints for red/blue team would be suitable for the centre location.
(With a configurable delay would be also good.)
Sorry if I made too many tickets in short term

**Comment by Shynixn** [comment]
Sounds interesting, should be possible to add that. 

Don't worry about that, as long as you create single tickets for single tasks it's great. However, don't expect me to finish all of them in the near future ;)

**Comment by LazoYoung** [comment]
Yes I'm a developer and I've been looking into contributing your project.
But I'm not sure when I can make free time
