### ISSUE TITLE
Delay (cooldown) for double-jumps

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#44]
Overuse of double jumps could annoy the players if there are many players in one arena.
We need an option this cooldown length for our arena.

Below this is just my idea note for the future which may be off-topic:

- Players are separated into their own position (Forward, Defend, GK)
- Forward & defenders have long delay for double-jumps but short delay for ball kick delay.
- GK has short delay for double jump as he/she wants to make goal saves

**Comment by Shynixn** [comment]
I like the idea of a cooldown for double jumps. I will definitely add this in the future. 

However, I don't really know if it's fitting to split players into specific roles in games.  I might consider it later but still nice idea.

**Comment by LazoYoung** [comment]
I don't mind if player roles idea can't be implemented in the future, thanks for considering it :)

**Comment by Shynixn** [comment]
- Ball Physic engine added in 5.0.1
