### ISSUE TITLE
Remove stats tracking database indefinitely

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/BlockBall#451]
The stats tracking database did not get used very often considering how much cpu time it wastes on async threads. It should be removed.

**Comment by rautamiekka** [comment]
Maybe this could be replaced by an API, maybe an event system (I dunno, just how I've seen something being done), that other plugins could use ?

**Comment by Shynixn** [comment]
You can track it yourself using BlockBall events. 
https://github.com/Shynixn/BlockBall/tree/master/blockball-bukkit-api/src/main/java/com/github/shynixn/blockball/api/bukkit/event

**Comment by rautamiekka** [comment]
Eeyep, I didn't try checking if such thing existed already, and it backfired ...
