### ISSUE TITLE
The minigame scoreboard limits the scoreboard texts to 15 characters

### ISSUE THREAD

**Issue by JVNfsOficial** [Shynixn/BlockBall#457]
The minigame scoreboard limits the scoreboard texts to 15 characters, even using other scoreboard plugins it gives an error and I can't use the scoreboard as I wanted, could there be a way to increase this character limit? (Google translator)

**Comment by Shynixn** [comment]
No there isn't a way to change the BlockBall scoreboard. You use a dedicated scoreboard plugin instead, which is able to display placeholder api placeholders.
