### ISSUE TITLE
New Placeholders to create

### ISSUE THREAD

**Issue by iFooh** [Shynixn/BlockBall#468]
Add new placeholders either using the same plugin or using the Placeholders API

(I'm replacing < > with { } because GitHub doesn't detect it)
Examples in Match:
 - {yourteam} - See which team you are on
 - {yourteamcolor} -The color of your team that you are
 - {goalsinmatch} - Your goals in a game (Minigame)
 - {assistsinmatch}- Your assists in a game (Minigame)
 - {finalscoreinmatch} -When you see the average of goals and assists, get an average of 1 to 5 for the player

Examples in Per-player: (Using PlaceholderAPI)
 - %blockball_{mode}_goals% - See your total goals (<mode>It's the arena game mode: Hubgame, Minigame or BungeecordGame)
 - %blockball_{mode}_assists% - See your total assists
 - %blockball_{mode}_goalrate% - See your average goals per game
 - %blockball_{mode}_assistrate% - See your average assists per game
 - %blockball_{mode}_wins% - See your total wins
 - %blockball_{mode}_ties% - See your total ties
 - %blockball_{mode}_losses% - See your total losses

Those are the new or best placeholders, the others are fine

I know there are some repeated ones and some new ones, but some don't work and others get an error from the scoreboard when using them.

I would like them to return the use of PlaceholderAPI for blockball, they have a complete and detailed API

Another thing I would like would be for you to see the Scoreboard better and for it not to have the maximum characters error, apart from supporting Placeholders in the Scoreboards and Titles

Sorry for the poor English, I use google translate

**Comment by Shynixn** [comment]
BlockBall does not track your wins, goals or losses anymore, sorry. You can only script that yourself using the BlockBall api.

The list of current placeholders can be found here. https://shynixn.github.io/BlockBall/build/html/customizing/placeholders.html

For the max scoreboard characters, please use a dedicated scoreboard plugin with PlaceHolderApi support. BlockBall only offers a very basic scoreboard integration, not a complete one.

**Comment by iFooh** [comment]
I understand the first thing, but about the scoreboard, on my server it does not detect any Placeholderapi variable in it, could you tell me a good plugin to use it?

**Comment by Shynixn** [comment]
Maybe you have got the wrong placeholder values? I am not sure about modern scoreboard plugins, search for scoreboard plugins on spigot or bukkit.
