### ISSUE TITLE
Grab and Throw problem

### ISSUE THREAD

**Issue by Frodamin** [Shynixn/BlockBall#469]
So, i need help cus in config of ball in particles and sound effects there is a option to configure grab and throws but idk how to use them and turn them on in settings

**Comment by Shynixn** [comment]
These are left over settings. Sorry, grabbing and throwing has not been working for some years now.

**Comment by Frodamin** [comment]
is there any ideas of getting it back?

**Comment by Frodamin** [comment]
like im dev of this plugin and football on one of the polish blockball servers so im rn looking for optimization of goalkeeper role
in a game

**Comment by Shynixn** [comment]
Currently, there are no plans to add this back. It was not used that often and made the game more complicated for casual plays. 

I see, well this feature needs a lot of work + prototyping as the previous implementation caused things such as item duplication on servers.
