### ISSUE TITLE
Basket Ball plugin ?

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/BlockBall#49]
Hi ! :D

Could you a Basket Ball plugin ? :D 

Thanks ! :D

**Comment by Shynixn** [comment]
When the anniversary update is finished, I'll think about it ;)

**Comment by TheIntelloBox** [comment]
Yeah ! :D What will be the anniversary update ? :D

**Comment by TheIntelloBox** [comment]
When will be the update ?

**Comment by Shynixn** [comment]
Yeah yeah, but it takes some time...

**Comment by LazoYoung** [comment]
This is a football plugin, basically not for basketball.. The idea is nice but developer can't make everything possible
