### ISSUE TITLE
Major Bug: Users get Fly after game!

### ISSUE THREAD

**Issue by ScuroK** [Shynixn/BlockBall#5]
After a game players are able to FLY! While admins become unable to fly after game.

Can you fix this major bug?

**Comment by ScuroK** [comment]
Die Spieler können nach dem Spiel FLIEGEN! :S

**Comment by Shynixn** [comment]
Can you please provide me your arena.yml file (pastebin) where this problem happend and tell me if you are using Essentials?

**Comment by ScuroK** [comment]
I already deleted my blockarena folder. It was a normal arena (default). 
Commands on end: minecraft:teleport :player <Coords>
Commands on win: give :player 357 1

Double jump was on.

I also activated the option to respawn the player at a certain location to prevent respawning inside the arena.

On the spigot forums i found an old post where another player had the same issue.

**Comment by ScuroK** [comment]
What is very interesting is that my admin was unable to fly anymore after the game while players who should not be able to fly could xD
Why does blockball even interact with things like fly? Do you think you can fix it?

**Comment by Shynixn** [comment]
Hm... I have published snapshot 3.8.0-2 that should resolve that issue.
 You can download it via the snapshots.  Filename: 'blockball-3.8.0-20170126.162941-2.jar'

**Comment by ScuroK** [comment]
i will try. Thanks alot!

**Comment by ScuroK** [comment]
@Shynixn I tested it. the player was not able to fly after the game. BUT i lost my flight mode. after typing /fly i could fly again.

**Comment by ScuroK** [comment]
@Shynixn Kannst du deutsch? Es sieht jetzt folgendermassen aus:
blockball-3.8.0-20170126.162941-2.jar macht folgendes:
Nach dem Spiel verliere ich (OP) zwar fly, kann es aber mit /fly wieder aktivieren. Mein ADMIN (Nicht OP) verliert Fly und kann es NICHT aktivieren. Erst nachdem er den Server neu joint kann er wieder fliegen! Der normale Spieler hatte diesesmal kein fly mehr nach dem Spiel. Ich sende dir gleich noch die files ok?

**Comment by ScuroK** [comment]
@Shynixn 
arena.yml:
http://pastebin.com/bntBr7Di

config.yml:
http://pastebin.com/r0agxi8y

log:
http://pastebin.com/1RiAhCcq

Hilft dir das weiter?

**Comment by ScuroK** [comment]
its still a bit creepy to see blockball playing arround with fly to be be honest :S

**Comment by Shynixn** [comment]
Kann gerne auch auf Deutsch schreiben, nur werden andere, die auf diesen Issue drücken, die Antworten nicht lesen können. ^^

Danke für die schnelle Rückmeldung, ich hab den FlyStatus der einzelnen Spieler nicht zwischengespeichert, darum wird das wohl auftreten. Kann das aber noch ändern :)

**Comment by ScuroK** [comment]
wäre hammer! :) danke

**Comment by ScuroK** [comment]
@Shynixn kannst du es als snapshot hochladen wenn du es geschafft hast? :)

**Comment by Shynixn** [comment]
Sollte passen. Snapshot: 'blockball-3.8.0-20170126.230420-3.jar'

**Comment by ScuroK** [comment]
Du bist der Beste! Vielen Dank!! Ich werde es heute Abend testen :)
Das wäre das erste brauchbare Fussballplugin das ich jemals gesehen habe! :D

**Comment by ScuroK** [comment]
@Shynixn man verliert immernoch fly nach dem spiel. admins müssen relogen. aber immerhin besser als fly zu bekommen... warum interagiert das plugin denn überhaupt mit fly? braucht es das für den doppeljump?

**Comment by ScuroK** [comment]
Ich habe etwas herausgefunden!

1. ich (op) spiele eine runde blockball
2. nach ende des spiels verliere ich fly
3. ich aktiviere es wieder mit /fly
4. ich lösche arena
5. sobald ich die arena gelöscht habe, fliege ich wieder vom himmel. fly ist weg.

irgendwie wird die sache immer verwirrender!! xD :S

**Comment by Shynixn** [comment]
BlockBall brauchts leider damit Double Jumps funktionieren...  Seltsam, ich hab den Fehler nicht mehr....
Ich schau mal ob ich noch was finde.

**Comment by ScuroK** [comment]
bist du sicher dass du nicht versehentlich die alte version als snapshot hochgeladen hast?

**Comment by ScuroK** [comment]
@Shynixn mein server benutzt dieses Plugin:
https://www.spigotmc.org/resources/jumppads-test-server-ip-play-pixelcraftmc-com.29773/

Denkst du es hat was damit zu tun?

**Comment by ScuroK** [comment]
Mein Server benutzt nebenbei noch ein JumpPad-Plugin:
https://www.spigotmc.org/resources/jumppads-test-server-ip-play-pixelcraftmc-com.29773/

Denke aber nicht dass es daran liegt. Ich habe kein Jump-pad berührt während den tests.

**Comment by Shynixn** [comment]
Nein nein ;) 

Bei der Release Versionen muss ich es manuell hochladen, da könnte ich wirklich nen Fehler machen aber die Snapshot Versionen werden automatisch mit allen zusätzlichen Dateien hochgeladen und veröffentlicht.
Der Zeitpunkt steckt auch im Dateinamen 20170126.230420 -> 26 01 2016 23:04:20 .

Warum gibt du deinen Admins eigentlich nicht die Toggle Fly Permission, also zugriff zum /fly Kommando?

**Comment by ScuroK** [comment]
@Shynixn warum nicht? als Admins müssen sie in gewissen Situationen fliegen können. 
Gibt es denn keine andere Möglichkeit für den Doppeljump?

Ein andere Idee wäre folgendes: Könntest du machen, dass wenn Doppeljump deaktiviert ist, kein Einfluss auf den Fly-Status des Spielers vonseiten des Plugins genommen wird?

Also wenn Doppeljump aus ist, sollte einfach alles bypassed werden was Blockball mit Fly machen würde. Das wäre wohl gut genug. Dann kann man selber wählen ob man diesen kleinen "Bug" in kauf nimmt oder auf Doppeljump verzichtet :)

**Comment by ScuroK** [comment]
Sonst wäre es ja kein BUg. Sie müssten einfach /fly machen nach einem Spiel.
Wenn dies Aber nicht möglich ist, sehe ich es schon als Problem :/

**Comment by ScuroK** [comment]
Oh oder meintest du du hast gefixt, das der command /fly nicht mehr geblockt wird für nicht-ops?
das habe ich nämlich noch nicht getestet.

**Comment by ScuroK** [comment]
Jedenfalls können normale spieler nicht mehr fliegen so wie es aussieht :)
