### ISSUE TITLE
Signs bug.

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/BlockBall#60]
Hey,

signs:
        '1':
          x: 10058.0
          y: 206.0
          z: -89899.0
          yaw: 0.0
          pitch: 0.0
          world: Parkour

But look the screen : https://zupimages.net/up/18/09/mfmf.jpg

And it's the same for all the signs.

**Comment by LazoYoung** [comment]
Did you give it a try deleting the sign (including the configuration set) and then re-place it with command UI?

**Comment by Shynixn** [comment]
Please tell me the gamemode you are using (Hubgame, Minigame, Bungeecord) and if the game is already started.

**Comment by TheIntelloBox** [comment]
Minigame and no the game isn't started.

**Comment by Shynixn** [comment]
Thanks, I'll take a look into this.
