### ISSUE TITLE
i have that error at the end of the game

### ISSUE THREAD

**Issue by friishon** [Shynixn/BlockBall#61]
https://hastebin.com/wadofarolu.vbs

and can you change the ball mechanic and make it like hypixel?? and is it possible to make round the ball??

**Comment by LazoYoung** [comment]
You should accept that hypixel has own plugin for their games.  
This plugin has nothing to do with it

**Comment by friishon** [comment]
i only ask if he can, i'm not forcing him to make like hypixel

**Comment by Shynixn** [comment]
Thanks for reporting, this error will be fixed next version! 

The ball on hypixel uses some kind of serverside texturepack if I'm right, the ball mechanic stays like this for now. I'll only make minor changes.

**Comment by friishon** [comment]
thanks :D
