### ISSUE TITLE
Minor(?) issues on various aspects

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#62]
Although there are few minor problems remaining, I'm convinced that this update is the best one, which significantly improved this plugin in ball physics and UI changes.
Nice work, shynixn! 👍 

### Game system, UI
* [x] Should force to change gamemode on join
* [x] /bbleave won't teleport you to the specified leave spawnpoint.
* [ ] As soon as the game starts, notice players which team they're in

### Game physics
- [x] **EDIT**: It is hard to make goals. There are 2 cases that make goal harder:
  - If goal area is thin, it won't count any goals. (This is trivial)
  - Goal area sometimes act as a WALL, blocking shots on target (especially higher shots).
- [x] Skeleton skull is occasionally placed when throwing off the ball with right click

**Comment by Shynixn** [comment]
Of course, there are many minor problems as this plugin has got too options to test all features alone. Thank you, I also think this was the right way. :)

Also, thanks for testing all of this and your thoughts on BlockBall. I'll try to fix this issues as soon as possible to get it completely ready for production. 

I don't really get what you mean by the issue that goal area sometimes acts as a wall?

**Comment by LazoYoung** [comment]
When your shot is on target, it bounces back rather than getting into the net.

**Comment by Shynixn** [comment]
ok, I'll take a look.

**Comment by Shynixn** [comment]
Bugs should be resolved now, the enhancements get added in the near future.

**Comment by LazoYoung** [comment]
Is the goal detection fix still on progress?

**Comment by Shynixn** [comment]
Yes, I could automatically increase the size of the set goal to match a minimum size, so it won't appear. The wall bouncing though, is a different question as it's detection works by using the NMS code of block collisions. I would say it's the admin's duty to change the selection for the goal depending on their goal format?

**Comment by LazoYoung** [comment]
You mean my goal selection is the cause of wall bouncing? Well that was unexpected... Then please tell me how to select a goal in a valid way.

**Comment by Shynixn** [comment]
Well, it depends on your goal and we selection. I don't know what to add.

**Comment by LazoYoung** [comment]
Can you take a look at [this video](https://youtu.be/h-R1_c10i8o) I've recorded?

**Comment by Shynixn** [comment]
Sorry for replying so late, yes I have taken a look at your video. This behavior is strange and of course not acceptable. I'm going to try to replicate and fix it, thanks for the video it made things more clear 👍

**Comment by Shynixn** [comment]
@LazoYoung I have found a bug in the [ball collision](https://github.com/Shynixn/Ball/issues/5) and fixed it in the latest snapshot. It should resolve the problem with the goals.

[Direct Snapshot Download](https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/blockball/blockball-bukkit-plugin/5.0.3-SNAPSHOT/blockball-bukkit-plugin-5.0.3-20180316.204739-3.jar)
