### ISSUE TITLE
Shots at goal / penaltys.

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/BlockBall#76]
Could you add the penaltys ? (I don't know if this word is good in English).

**Comment by Shynixn** [comment]
I don't know it either ^^.  For what reason should Players receive penalties?

**Comment by TheIntelloBox** [comment]
That could be a gamemode, or I don't know. xD

**Comment by LazoYoung** [comment]
Though this could be challenging and take much time, I believe this idea would fit the concept of reality in role-playing soccer.  
Remember my thoughts on team roles? You may consider #43 if you're interested :D

**Comment by TheIntelloBox** [comment]
Yeah would be nice.
