### ISSUE TITLE
Minigame-mode not working? signs not working?

### ISSUE THREAD

**Issue by ScuroK** [Shynixn/BlockBall#79]
Latest official version:

If i use MINIGAME mode the "join any team" sign does nothing but removes the whole inventory forever.
i can only use the HUB mode right now.

**Comment by Shynixn** [comment]
Thanks for reporting, the minigame mode should put you into a lobby before starting a game. If the countdown does not start in the exp bar then there should be atleast an error message?

**Comment by Shynixn** [comment]
Cannot confirm, minigame mode works as expected. As I mentioned without an error log of yours or steps to reproduce the issue I cannot help you.

**Comment by ScuroK** [comment]
i forgot to set the lobby spawn point. sorry for the confusion :S

**Comment by Shynixn** [comment]
Ok thanks, I thought a warning message would pop put when you forget to set the lobby spawnpoint or leaving spawnpoint.
