### ISSUE TITLE
Scheduled Events

### ISSUE THREAD

**Issue by FeroxDrood** [Shynixn/BlockBall#84]
Hey,

I would love to see the addition of the ability to set Scheduled events. This would allow for games to automatically start at certain times through the day so say 12am, 3am, 6am, 9am, 12pm, 3pm, 6pm and 9pm.

(Sorry is this is already possible i'm fairly new to the plugin.

**Comment by Shynixn** [comment]
Hi!
No this isn't possible at the moment. There are 3 different modes as you can read at the [wiki](https://shynixn.github.io/BlockBall/build/html/index.html).

There is not really a mode for for events, so can you describe what you mean with event games? I would suggest to get in touch with the plugin first though.
