### ISSUE TITLE
Impossible to score.

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/BlockBall#91]
Hey,

I have set correctly my map but if we put the ball in the goal, nothing happens.
My arena.yml : https://pastebin.com/VcQ6ipRz
My config.yml : https://pastebin.com/rM9fbWCS

**Comment by TheIntelloBox** [comment]
?

**Comment by Shynixn** [comment]
I'm going to check it later.

**Comment by TheIntelloBox** [comment]
Did you check ?

**Comment by Shynixn** [comment]
I'll probably find time for a bug fixing session of BlockBall next weekend. For speeding up the development process I have set up my patreon page. Can you paste your arena config into a gist as the pastbin links seem to be already offline?

**Comment by TheIntelloBox** [comment]
https://gist.github.com/TheIntelloBox/cb3effae34d20c1d4841f519ae477765

**Comment by Shynixn** [comment]
Try to increase the thicknbess of the goal. The minecraft tickrate is a way to slow to detect a fast flying ball in a "2D" goal. Simply select some room behind the goal, even if it's outside the arena, to allow the plugin detecting the location of the ball.

Making the goals work requires some playing around but it should always be a cube with width, height and length atleast >= 2

team-blue:
`        corner-1:
          **x: 10092.0**
          y: 205.0
          z: -89895.0
          yaw: 0.0
          pitch: 0.0
          world: world
        corner-2:
          x: 10092.0
          y: 203.0
          z: -89900.0
          yaw: 0.0
          pitch: 0.0
          world: world`

Increase the x (for example, I don't know your building):
`        corner-1:
          **x: 10094.0**
          y: 205.0
          z: -89895.0
          yaw: 0.0
          pitch: 0.0
          world: world
        corner-2:
          x: 10092.0
          y: 203.0
          z: -89900.0
          yaw: 0.0
          pitch: 0.0
          world: world`

team red:
`        corner-1:
          **x: 10170.0**
          y: 205.0
          z: -89895.0
          yaw: 0.0
          pitch: 0.0
          world: world
        corner-2:
          x: 10170.0
          y: 203.0
          z: -89900.0
          yaw: 0.0
          pitch: 0.0
          world: world`

Increase the x (for example, I don't know your building):

`        corner-1:
          **x: 10174.0**
          y: 205.0
          z: -89895.0
          yaw: 0.0
          pitch: 0.0
          world: world
        corner-2:
          x: 10170.0
          y: 203.0
          z: -89900.0
          yaw: 0.0
          pitch: 0.0
          world: world`

**Comment by TheIntelloBox** [comment]
Works only for the blue goal.

**Comment by Shynixn** [comment]
Just keep playing around with the selection, it's better to be generous with it.

**Comment by Shynixn** [comment]
Please increase the height too, 1 block is just too small for the hitbox detection.

**Comment by TheIntelloBox** [comment]
I did it, it doesn't work.

**Comment by Shynixn** [comment]
I'm quite sure that it works as I have got lots of different configured arenas on my testing server. Just select a big cube and check if the goal gets registered once the ball goes into it. I don't know anything else to suggest, you can watch the old youtube videos as the goal selection works exactly the same like now?

**Comment by TheIntelloBox** [comment]
goal:
        corner-1:
          x: 10169.0
          y: 202.0
          z: -89895.0
          yaw: 0.0
          pitch: 0.0
          world: Parkour
        corner-2:
          x: 10175.0
          y: 206.0
          z: -89900.0
          yaw: 0.0
          pitch: 0.0
          world: Parkour

**Comment by TheIntelloBox** [comment]
Please... it doesn't work...

**Comment by Shynixn** [comment]
Sorry, seems like I got kicked from your server. Glad that I could help you out. :)

Don't forget to remove the permissions from my player name afterwards.
About your question of the Basketball plugin. The engine BlockBall uses already contains a way to grab and throw the ball, however I don't think I'm going to implement a BasketBall game any time soon. You can try it by setting ball.carry-able: true in the arena config and rightclicking the ball but don't use this option in real games yet.

**Comment by TheIntelloBox** [comment]
Thank you for your work and your answer. :D
